<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>10.0</LangVersion>
    
    <!-- ✅ ما يطلعش pdb في Release -->
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    
    <!-- ✅ ما يطلعش app.config -->
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <ApplicationIcon>Assets\Icons\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Avatars\Avatar.jpg" />
    <None Remove="Assets\Icons\Logo.png" />
    <None Remove="Fonts\AR-Font.ttf" />
    <None Remove="Fonts\EN-Font.ttf" />
    <None Remove="Fonts\ES-Font.ttf" />
    <None Remove="Fonts\FR-Font.ttf" />
    <None Remove="Fonts\RU-Font.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Lang\Lang-AR.xaml" />
    <Page Remove="Lang\Lang-EN.xaml" />
    <Page Remove="Lang\Lang-ES.xaml" />
    <Page Remove="Lang\Lang-FR.xaml" />
    <Page Remove="Lang\Lang-RU.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Avatars\Avatar.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Icons\icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.8.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\Logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\AR-Font.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\EN-Font.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\ES-Font.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\FR-Font.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RU-Font.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Lang\Lang-AR.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Lang\Lang-EN.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Lang\Lang-ES.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Lang\Lang-FR.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Lang\Lang-RU.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>